/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BOB;

/**
 *
 * @author Администратор
 */
public class mainForm extends javax.swing.JFrame {

    /**
     * Creates new form mainForm
     */
    public mainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        openBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        favBtn = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jLabel11 = new javax.swing.JLabel();
        presets = new javax.swing.JComboBox();
        setupPanel = new javax.swing.JPanel();
        bit5Panel = new javax.swing.JPanel();
        bit5Slider = new javax.swing.JSlider();
        bit5Label = new javax.swing.JLabel();
        bit4Panel = new javax.swing.JPanel();
        bit4Slider = new javax.swing.JSlider();
        bit4Label = new javax.swing.JLabel();
        bit8Panel = new javax.swing.JPanel();
        bit8Slider = new javax.swing.JSlider();
        bit8Label = new javax.swing.JLabel();
        bit3Panel = new javax.swing.JPanel();
        bit3Slider = new javax.swing.JSlider();
        bit3Label = new javax.swing.JLabel();
        bit6Panel = new javax.swing.JPanel();
        bit6Slider = new javax.swing.JSlider();
        bit6Label = new javax.swing.JLabel();
        bit1Panel = new javax.swing.JPanel();
        bit1Slider = new javax.swing.JSlider();
        bit1Label = new javax.swing.JLabel();
        bit7Panel = new javax.swing.JPanel();
        bit7Slider = new javax.swing.JSlider();
        bit7Label = new javax.swing.JLabel();
        bit2Panel = new javax.swing.JPanel();
        bit2Slider = new javax.swing.JSlider();
        bit2Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        openBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/OpenPic.png"))); // NOI18N
        openBtn.setToolTipText("");
        openBtn.setFocusable(false);
        openBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        openBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        openBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(openBtn);

        saveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/SavePic.png"))); // NOI18N
        saveBtn.setToolTipText("");
        saveBtn.setFocusable(false);
        saveBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        saveBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(saveBtn);
        jToolBar1.add(jSeparator1);

        favBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/SavePreset.png"))); // NOI18N
        favBtn.setFocusable(false);
        favBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        favBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(favBtn);
        jToolBar1.add(jSeparator2);

        jLabel11.setText("Presets ");
        jToolBar1.add(jLabel11);

        presets.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jToolBar1.add(presets);

        bit5Slider.setMaximum(17);
        bit5Slider.setOrientation(javax.swing.JSlider.VERTICAL);
        bit5Slider.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        bit5Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bit5Label.setText("00");

        javax.swing.GroupLayout bit5PanelLayout = new javax.swing.GroupLayout(bit5Panel);
        bit5Panel.setLayout(bit5PanelLayout);
        bit5PanelLayout.setHorizontalGroup(
            bit5PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bit5PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(bit5PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bit5Label, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bit5PanelLayout.createSequentialGroup()
                        .addComponent(bit5Slider, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        bit5PanelLayout.setVerticalGroup(
            bit5PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bit5PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bit5Slider, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bit5Label))
        );

        bit4Slider.setMaximum(17);
        bit4Slider.setOrientation(javax.swing.JSlider.VERTICAL);
        bit4Slider.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        bit4Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bit4Label.setText("00");

        javax.swing.GroupLayout bit4PanelLayout = new javax.swing.GroupLayout(bit4Panel);
        bit4Panel.setLayout(bit4PanelLayout);
        bit4PanelLayout.setHorizontalGroup(
            bit4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bit4PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(bit4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bit4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bit4PanelLayout.createSequentialGroup()
                        .addComponent(bit4Slider, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        bit4PanelLayout.setVerticalGroup(
            bit4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bit4PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bit4Slider, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bit4Label))
        );

        bit8Slider.setMaximum(17);
        bit8Slider.setOrientation(javax.swing.JSlider.VERTICAL);
        bit8Slider.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        bit8Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bit8Label.setText("00");

        javax.swing.GroupLayout bit8PanelLayout = new javax.swing.GroupLayout(bit8Panel);
        bit8Panel.setLayout(bit8PanelLayout);
        bit8PanelLayout.setHorizontalGroup(
            bit8PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bit8PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(bit8PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bit8Label, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bit8PanelLayout.createSequentialGroup()
                        .addComponent(bit8Slider, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        bit8PanelLayout.setVerticalGroup(
            bit8PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bit8PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bit8Slider, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bit8Label))
        );

        bit3Slider.setMaximum(17);
        bit3Slider.setOrientation(javax.swing.JSlider.VERTICAL);
        bit3Slider.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        bit3Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bit3Label.setText("00");

        javax.swing.GroupLayout bit3PanelLayout = new javax.swing.GroupLayout(bit3Panel);
        bit3Panel.setLayout(bit3PanelLayout);
        bit3PanelLayout.setHorizontalGroup(
            bit3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bit3PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(bit3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bit3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bit3PanelLayout.createSequentialGroup()
                        .addComponent(bit3Slider, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        bit3PanelLayout.setVerticalGroup(
            bit3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bit3PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bit3Slider, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bit3Label))
        );

        bit6Slider.setMaximum(17);
        bit6Slider.setOrientation(javax.swing.JSlider.VERTICAL);
        bit6Slider.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        bit6Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bit6Label.setText("00");

        javax.swing.GroupLayout bit6PanelLayout = new javax.swing.GroupLayout(bit6Panel);
        bit6Panel.setLayout(bit6PanelLayout);
        bit6PanelLayout.setHorizontalGroup(
            bit6PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bit6PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(bit6PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bit6Label, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bit6PanelLayout.createSequentialGroup()
                        .addComponent(bit6Slider, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        bit6PanelLayout.setVerticalGroup(
            bit6PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bit6PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bit6Slider, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bit6Label))
        );

        bit1Slider.setMaximum(17);
        bit1Slider.setOrientation(javax.swing.JSlider.VERTICAL);
        bit1Slider.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        bit1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bit1Label.setText("00");

        javax.swing.GroupLayout bit1PanelLayout = new javax.swing.GroupLayout(bit1Panel);
        bit1Panel.setLayout(bit1PanelLayout);
        bit1PanelLayout.setHorizontalGroup(
            bit1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(bit1PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(bit1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bit1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bit1PanelLayout.createSequentialGroup()
                        .addComponent(bit1Slider, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        bit1PanelLayout.setVerticalGroup(
            bit1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bit1PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bit1Slider, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bit1Label))
        );

        bit7Slider.setMaximum(17);
        bit7Slider.setOrientation(javax.swing.JSlider.VERTICAL);
        bit7Slider.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        bit7Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bit7Label.setText("00");

        javax.swing.GroupLayout bit7PanelLayout = new javax.swing.GroupLayout(bit7Panel);
        bit7Panel.setLayout(bit7PanelLayout);
        bit7PanelLayout.setHorizontalGroup(
            bit7PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bit7PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(bit7PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bit7Label, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bit7PanelLayout.createSequentialGroup()
                        .addComponent(bit7Slider, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        bit7PanelLayout.setVerticalGroup(
            bit7PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bit7PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bit7Slider, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bit7Label))
        );

        bit2Slider.setMaximum(17);
        bit2Slider.setOrientation(javax.swing.JSlider.VERTICAL);
        bit2Slider.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        bit2Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bit2Label.setText("00");

        javax.swing.GroupLayout bit2PanelLayout = new javax.swing.GroupLayout(bit2Panel);
        bit2Panel.setLayout(bit2PanelLayout);
        bit2PanelLayout.setHorizontalGroup(
            bit2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bit2PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(bit2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bit2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bit2PanelLayout.createSequentialGroup()
                        .addComponent(bit2Slider, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        bit2PanelLayout.setVerticalGroup(
            bit2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bit2PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bit2Slider, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bit2Label))
        );

        javax.swing.GroupLayout setupPanelLayout = new javax.swing.GroupLayout(setupPanel);
        setupPanel.setLayout(setupPanelLayout);
        setupPanelLayout.setHorizontalGroup(
            setupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(setupPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bit1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bit2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bit3Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bit4Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bit5Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bit6Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bit7Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bit8Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        setupPanelLayout.setVerticalGroup(
            setupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(setupPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(setupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bit1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bit2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bit3Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bit4Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bit5Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bit6Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bit7Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bit8Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(setupPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 411, Short.MAX_VALUE)
                .addComponent(setupPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_openBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bit1Label;
    private javax.swing.JPanel bit1Panel;
    private javax.swing.JSlider bit1Slider;
    private javax.swing.JLabel bit2Label;
    private javax.swing.JPanel bit2Panel;
    private javax.swing.JSlider bit2Slider;
    private javax.swing.JLabel bit3Label;
    private javax.swing.JPanel bit3Panel;
    private javax.swing.JSlider bit3Slider;
    private javax.swing.JLabel bit4Label;
    private javax.swing.JPanel bit4Panel;
    private javax.swing.JSlider bit4Slider;
    private javax.swing.JLabel bit5Label;
    private javax.swing.JPanel bit5Panel;
    private javax.swing.JSlider bit5Slider;
    private javax.swing.JLabel bit6Label;
    private javax.swing.JPanel bit6Panel;
    private javax.swing.JSlider bit6Slider;
    private javax.swing.JLabel bit7Label;
    private javax.swing.JPanel bit7Panel;
    private javax.swing.JSlider bit7Slider;
    private javax.swing.JLabel bit8Label;
    private javax.swing.JPanel bit8Panel;
    private javax.swing.JSlider bit8Slider;
    private javax.swing.JButton favBtn;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton openBtn;
    private javax.swing.JComboBox presets;
    private javax.swing.JButton saveBtn;
    private javax.swing.JPanel setupPanel;
    // End of variables declaration//GEN-END:variables
}
